name: Generate PDF from Markdown
on: push
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
          echo "files_old=$(printf '"%s" ' *.md)"
          echo "files=$(find . -type f -name '*.md')" > $GITHUB_OUTPUT

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/output.pdf ${{ steps.files_list.outputs.files }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
